services:
  backend:
    build: .
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - PYTHON_ANALISE_URL=http://python:8000/analisar
    networks:
      - sprintjava-net

networks:
  sprintjava-net:
    external: true
