services:
  backend:
    build: .
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - sprintjava-net

networks:
  sprintjava-net:
    external: true

